// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgoltkclzrlqrkdnvjco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indnb2x0a2NsenJscXJrZG52amNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzI1ODEsImV4cCI6MjA2Mzk0ODU4MX0.5H5S-yGB0zQDlYNRjXGSshyCCzT4ZIzpZnXMDqshKtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);